services:
  - type: web
    name: saregama
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
    disk:
      name: data
      mountPath: /opt/render/project/src/backend/.data
      sizeGB: 1
